### ISSUE TITLE
Attribute Error while saving

### ISSUE THREAD

**Issue by noidavoid** [audioscavenger/save-image-extended-comfyui#3]
Sorry to bother you, the node appears to be functioning just fine despite the error I'm just more annoyed the error comes up. Is there anyway to fix this?

```
!!! Exception during processing!!! 'int' object has no attribute 'endswith'
!!! Exception during processing!!! 'int' object has no attribute 'endswith'
Traceback (most recent call last):
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\wx-save-image-extended-comfyui\save_image_extended.py", line 330, in save_images
    SaveImageExtended.save_job_to_json(save_job_data, prompt, filename_prefix, positive_text_opt, negative_text_opt, job_custom_text, resolution, output_path, 'jobs.json')
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\wx-save-image-extended-comfyui\save_image_extended.py", line 175, in save_job_to_json
    models = SaveImageExtended.find_parameter_values(['ckpt_name', 'loras', 'vae_name', 'model_name'], prompt)
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\wx-save-image-extended-comfyui\save_image_extended.py", line 131, in find_parameter_values
    SaveImageExtended.find_parameter_values(target_keys, value, found_values)
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\wx-save-image-extended-comfyui\save_image_extended.py", line 131, in find_parameter_values
    SaveImageExtended.find_parameter_values(target_keys, value, found_values)
  File "G:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\wx-save-image-extended-comfyui\save_image_extended.py", line 120, in find_parameter_values
    if value.endswith('.safetensors'):
AttributeError: 'int' object has no attribute 'endswith'
```

Edit:
Okay this only seems to appear when "basic, models, sampler, prompt" is selected for job data

**Comment by audioscavenger** [comment]
Very sorry you experienced this error. You are not using the latest master version. if you look at line 120, 131 and 330, nothing matches.
please pull the latest update, restart Comfy and retry.

**Comment by audioscavenger** [comment]
I believe "!! Exception during processing!!" comes from the original release. As indicated in ComfyUI manager, uninstall and reinstall the node to get my release instead.
